server:
  port: 8070

spring:
  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:db/${spring.sql.init.platform}/schema.sql
      data-locations: classpath:db/${spring.sql.init.platform}/data.sql
  datasource:
    url: jdbc:mysql://localhost:3306/sharing_car_test?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    suffix: .html
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: localhost
  messages:
    basename: message/messages
    encoding: UTF-8
    fallbackToSystemLocale: false
    alwaysUseMessageFormat: true
#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true
